version: "3.9"

services:
  test:
    image: wa-web-lib_test
    build:
      context: .
    volumes:
      - /d/Coding/Rust/ZTM/web-lib:/app
      - /d/Coding/Rust/ZTM/web-lib/node_modules:/app/node_modules
    working_dir: /app
    command: cargo watch -x test
    environment:
      NODE_ENV: test
    ports:
      - 3001:3000
